# Generated by Django 4.1 on 2023-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_clarityrating_rate_clarityrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default.png', upload_to='profile_pic/'),
        ),
    ]
